### ISSUE TITLE
null-ls generator throws error 

### ISSUE THREAD

**Issue by dekaravanhoc** [davidmh/cspell.nvim#68] opened 2024-10-03 16:42 UTC
**Describe the bug**
[null-ls] failed to run generator: ...a/Local/nvim-data/lazy/plenary.nvim/lua/plenary/path.lua:505: We couldn't mkdir: C:/Users/XXX/AppData/Local/Temp/nvim/cspell.nvim/C:%Users%XXX%AppData%Local%nvim

Seems to happen after the last update - null-ls still works only when cspell is added as a source, this comes up. 
I am using Windows.

**To Reproduce**
Use your plugin with null-ls on a windows machine.

**Additional context**
Great Plugin though. Helps a lot. :)

**Comment by davidmh** [comment] 2024-10-03 21:40
Hi @dekaravanhoc 

I don't have a Windows machine to test, but I can think of two possible root causes:

- The path in your error is using forward slashes, but windows paths should be backslashes, no?
   Sounds a lot like this issue: https://github.com/nvim-lua/plenary.nvim/issues/456
   Can you make sure your plenary.nvim dependency is using the latest release?
- This could also be related to the `C:` in the cached file we're trying to create for the combined config file.
   If the first option doesn't solve your problem, try sanitizing the path [here](https://github.com/davidmh/cspell.nvim/blob/33cb8570ab0dda1ad915347fae62567d9c1390ed/lua/cspell/helpers.lua#L67).
   See how we replace `/` with `%%`? I would try to remove the colons in that `merged_config_key`.

Let me know.

**Comment by dekaravanhoc** [comment] 2024-10-04 14:04
@davidmh 

I looked into it a little more. The Error you mentioned is not the issue and I run on the latest plenary version.
Path:mkdir() cant handle forward slashes on windows. Thats because of the underlying vim.loop.fs_mkdir function, which cant handle it.
Also the ":" is a problem.
I found the best solution to be using vim.fn.mkdir() as it handles all slashes between systems correctly,
So on [line 26](https://github.com/davidmh/cspell.nvim/blob/33cb8570ab0dda1ad915347fae62567d9c1390ed/lua/cspell/helpers.lua#L26) I would replace the plenary mkdir with: vim.fn.mkdir(cspell_json_directory_path, "p")
And on [line 67](https://github.com/davidmh/cspell.nvim/blob/33cb8570ab0dda1ad915347fae62567d9c1390ed/lua/cspell/helpers.lua#L67) I would add :gsub(":","") and change the % replacer to "-" (Extending Path on Windows looks for %, so it breaks there too later on.)

That solves the issue with the cache write. Unfortunatly there seems to be an issue with cspell not reading stdin://<path> correctly. At least on Windows. So I needed to just use stdin as the parameter for input [here](https://github.com/davidmh/cspell.nvim/blob/2c29bf573292c8f5053383d1be4ab908f4ecfc47/lua/cspell/diagnostics/init.lua#L26)

I opened issues on plenary and cspell for the mkdir and stdin stuff. Would be nice to get it back to working out of the bat again. :)

**Comment by hyogoa2c** [comment] 2024-10-31 06:54
I have same issue on my Windows 10 (Windows Terminal + Powershell). But works great in WSL.
Thanks for Great plugin.

**Comment by davidmh** [comment] 2024-11-01 01:50
I'm open to reviewing PRs adding support for windows. I don't have a windows machine, so I would be solving it in the dark. 

FWIW I think you could escape the path as described above and use the stdin param conditionally. The Lua api offers a few different ways to check for the current OS.

**Comment by davidmh** [comment] 2024-11-21 20:05
Solved in #72 (acdc6e5)

**Closed as completed by davidmh** 2024-11-21 20:05 UTC
Labels: help wanted, windows support
