### ISSUE TITLE
stdin:// prefix breaks cspell execution

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [davidmh/cspell.nvim#27] opened 2023-11-14 17:21 UTC
Hello, I'm using
```
nvim --version
NVIM v0.9.4
Build type: Release
LuaJIT 2.1.1697887905
```
```
cspell --version
6.17.0
```

And the latest version of this plugin and `null-ls`

Some time ago plugin stopped providing cspell diagnostics, so I've enabled debug mode for `null-ls`
and discovered that following command line is generated.

```
[DEBUG Tue Nov 14 17:01:16 2023] /home/eshepelyuk/.local/share/nvim/plugged/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:321: spawning command "cspell" at /home/eshepelyuk/xxx with args { "--show-suggestions", "-c", "/home/eshepelyuk/xxx/cspell.json", "lint", "--language-id", "markdown", "stdin:///home/eshepelyuk/xxx/docs/dev/index.md" }
[TRACE Tue Nov 14 17:01:16 2023] /home/eshepelyuk/.local/share/nvim/plugged/null-ls.nvim/lua/null-ls/helpers/generator_factory.lua:205: error output: CSpell: Files checked: 0, Issues found: 0 in 0 files
```

Ok, I've tried to run this command from my shell like

```
cspell --show-suggestions -c /home/eshepelyuk/xxx/cspell.json lint --language-id markdown stdin:///home/eshepelyuk/xxx/docs/dev/index.md
CSpell: Files checked: 0, Issues found: 0 in 0 files
```

When I remove `stdin://` - cspell works fine

```
cspell --show-suggestions -c /home/eshepelyuk/xxx/cspell.json lint --language-id markdown /home/eshepelyuk/xxx/docs/dev/index.md
1/1 ./docs/dev/index.md 678.43ms X
/home/eshepelyuk/xxx/docs/dev/index.md:3:25 - Unknown word (setip) Suggestions: [seti, setup, retip, stein, steep]
/home/eshepelyuk/xxx/docs/dev/index.md:29:74 - Unknown word (replacementtt) Suggestions:
 [replacement's, replacements, replacement]
CSpell: Files checked: 1, Issues found: 2 in 1 files
```

**Comment by davidmh** [comment] 2023-11-14 23:47
Hi @ievgenii-shepeliuk,

I'm having issues reproducing your problem, could you try recreating it using this template? https://github.com/davidmh/cspell-nvim-minimal-init

**Comment by eshepelyuk** [comment] 2023-11-14 23:54
> Hi @ievgenii-shepeliuk,
> 
> I'm having issues reproducing your problem, could you try recreating it using this template? https://github.com/davidmh/cspell-nvim-minimal-init

The issue is not neovim or plugin config. The issue is command line parameters passed to cspell, in particular prefixing the file name with `stdin://`

Just run cspell of mentioned version from command line against any file with typos, prefixing the file name with `stdin://`

**Comment by eshepelyuk** [comment] 2023-11-14 23:59
If tou can explain how to override args function via neovim config - that will solve the issue.

**Comment by davidmh** [comment] 2023-11-15 00:44
I understand the ask, but what I'm saying is that I don't see the problem that is showing up in the null-ls logs.

Before I change anything in the implementation I need to discard problems unique to your setup.

Or if the scenario is clear in your head, I could review a PR, you could thread a new option to disable that part of the command. You can see an example in #26, where I introduced the new option `read_config_synchronously`.

**Comment by ievgenii-shepeliuk** [comment] 2023-11-15 09:25
Hello @davidmh 

Looks like I've found a culprit.

According to the output of `cspell lint --help`

```
Examples:
    cspell "*.js"                   Check all .js files in the current directory
    cspell "**/*.js"                Check all .js files from the current directory
    cspell "src/**/*.js"            Only check .js under src
    cspell "**/*.txt" "**/*.js"     Check both .js and .txt files.
    cspell "**/*.{txt,js,md}"       Check .txt, .js, and .md files.
    cat LICENSE | cspell stdin      Check stdin
```

When the file is passed to `cspell` via stdin (as this plugin does) - 
the name of the file should be exactly `stdin`

I've tried running standalone `cspell` and it works.
```
cat test.md | cspell lint --language-id markdown stdin
```

Also I've implemented a PR #28 and it works for me in Neovim.

So, my current resolution is that the concatenation of real path must be removed from `args`
and the plugin should just pass `stdin` as the last parameter of `args`.

**Comment by davidmh** [comment] 2023-11-15 17:53
Maybe you're using a version of cspell that doesn't support the `stdin://` protocol, but it's definitely a valid option, see: https://github.com/streetsidesoftware/cspell/pull/4091

**Comment by eshepelyuk** [comment] 2023-11-15 17:59
> Maybe you're using a version of cspell that doesn't support the `stdin://` protocol, but it's definitely a valid option, see: https://github.com/streetsidesoftware/cspell/pull/4091

You are right,
i was sure that homebrew installs the latest available version, so haven't even checked which version is the latest now.
Will upgrade manually to 8.x and try again.

**Comment by davidmh** [comment] 2023-11-15 18:00
Let me know, if that's the issue I should add a comment about it in the README

**Comment by eshepelyuk** [comment] 2023-11-15 18:01
As a side note - maybe its possible to implement version check on startup ? To ensure that minimal compatible capell version is used ?

**Comment by davidmh** [comment] 2023-11-15 18:05
Maybe, yeah. I wonder if that would present any perf-related challenges, given that we would have to check per buffer, since CSpell can be loaded from the node packages with the `prefer_local` option.

**Comment by eshepelyuk** [comment] 2023-11-15 18:14
> Let me know, if that's the issue I should add a comment about it in the README

@davidmh confirmed 
working for me with the baseline plugin version and cspell 8.0 (the latest version)

Closing the issue.
The minimal cspell version should be added to docs.

Thanks for your patience and guidance.

**Comment by davidmh** [comment] 2023-11-15 18:17
Great, I'll add a comment later this week.

**Closed as completed by davidmh** 2023-11-15 18:17 UTC
