### ISSUE TITLE
Lose custom config after add to dictionary

### ISSUE THREAD

**Issue by sajadspeed** [davidmh/cspell.nvim#57] opened 2024-05-07 05:36 UTC
Hi, I want to use one `cspell` file for all projects. So I wrote the `find_json` function like this:
``` lua
local config = {
	--- A way to define your own logic to find the CSpell configuration file.
	---@params cwd The same current working directory defined in the source,
	--             defaulting to vim.loop.cwd()
	---@return string|nil The path of the json file
	find_json = function(cwd)
		return "/home/sajadspeed/.config/nvim/cspell.json" -- For global directory
	end,
}
```
And after that, I had a series of additional configs that I added to the `cspell` file, such as a second language and an additional dictionary:
``` json
{
	"language": "en, fa",
	"version": "0.2",
	"words": ["sajadspeed", "Interactable", "Behaviour", "UGUI", "texthl"],
	"flagWords": [],
	"dictionaries": ["vim"]
}
```
And now the problem is that every time I use `add to dictionary`, the `cspell.json` file is rewritten again and my configs are lost.

**Comment by davidmh** [comment] 2024-05-07 23:10
Hi @sajadspeed 

>  I want to use one cspell file for all projects. So I wrote the find_json function like this ...
> And after that, I had a series of additional configs that I added to the cspell file, such as a second language and an additional dictionary

Instead of using a custom path for a global config, I would recommend using one of the global paths recognized by the CSpell, something like:

- `~/.config/cspell.json`
- `~/cspell.json`

And then remove the `find_json` option from your config to let the plugin find local configurations when available.

Having a config file in the paths recognized by the CSpell cli would allow you to recognize words or dictionaries defined there, but update your local files.

Is that what you were looking for?

> And now the problem is that every time I use add to dictionary, the cspell.json file is rewritten again and my configs are lost.

Could you try reproducing the issue using this minimal config? https://github.com/davidmh/cspell-nvim-minimal-init

I would be easier for me to debug the problem if I can reproduce your issue.

**Comment by sajadspeed** [comment] 2024-05-08 07:23
> Is that what you were looking for?

Not exactly :) I want to have a global dictionary in addition to the global configs.  It means that when I use the `Add to dictionary` option, I can access that word in all my projects.  But, I think now, as you said, I can put my configs in the paths recognized by cspell and not change the `find_json` function anymore?

**Comment by davidmh** [comment] 2024-05-08 15:03
Cool. Give it a try and let me know.

**Comment by sajadspeed** [comment] 2024-05-09 10:49
> But, I think now, as you said, I can put my configs in the paths recognized by cspell and not change the find_json function anymore?

it's not working!
In its normal form `cspell` configuration file in the path:
`~/.config /cspell.json`
Its working but not in `cspell.nvim`.
Can't I do something to combine it with the global config when the `json` file is rebuilt after `Add to dictionary`?
The logic is that when `Add to dictionary` is called, only change the `words` in the `cspell.json` file, not rebuild the whole file.

**Comment by davidmh** [comment] 2024-05-09 16:00
> The logic is that when Add to dictionary is called, only change the words in the cspell.json file, not rebuild the whole file.

That's what should be happening now. Can you try to reproduce the problem with the minimal config I shared above? Having a reproducible environment would help me identify the problem.

**Comment by sajadspeed** [comment] 2024-05-09 23:54
Yes, I ran `minimal config` and global config **worked**.
I noticed that the path I was testing was actually the path where nvim's `cspell.json` file was located. So `cspell` [searched](https://cspell.org/configuration/imports/#importing-configuration) and automatically imported the `cspell.nvim` configuration file.
So I changed the path of the `find_json` function to this:
`/home/sajadspeed/.config/cspell.nvim.json`
And now I have two files in the config folder, one of which is the global configs file and the other is `cspell.nvim` configs.
Now, the problem is solved, but logically, `Add to dictionary` should not rebuild the entire `json` file, you only need to change the words. If this is corrected, for example, I can have a `cspell.json` file in the path of my project under the same conditions, and in addition to the normal global configs that I put in the same `find_json` path, I can also use the local configs.
In general, thank you very much for this great plugin that you made. I 'm not very familiar with `neovim` APIs, otherwise I would have added these options.

**Comment by davidmh** [comment] 2024-05-10 04:24
> Now, the problem is solved, but logically, Add to dictionary should not rebuild the entire json file, you only need to change the words. If this is corrected, for example, I can have a cspell.json file in the path of my project under the same conditions, and in addition to the normal global configs that I put in the same find_json path, I can also use the local configs.

This is the part that I don't understand about your problem. What do you mean by `Add to dictionary should not rebuild the entire json file`?

If you mean that the sorting of the keys and indentation changes, then that's a well know side effect of updating the file with Lua. The plugin uses the `vim.json` API, which transforms the contents of the cspell.json into a Lua table, so adding new words requires going from JSON to a Lua table and back to JSON. So the order of the encoded content can't be guaranteed.

What you may want to do in this case is to either:

- Specify a callback for `on_add_to_json` in the [configuration options](https://github.com/davidmh/cspell.nvim?tab=readme-ov-file#configuration-options), to ensure the sorting of the file with an external tool, like jq.
- Define your own `decode_json` and `encode_json` functions to use other decoding and encoding methods.

But if what you mean is that the contents of your file get replaced with just new content, then that's a bug. In that case, I would have to see the minimal config you created, along with the example of both the global config and the local configs you're using.

**Comment by sajadspeed** [comment] 2024-05-10 14:46
No, I mean, why when I made changes in the `cspell.json` file, such as changing the `language` or adding `dictionaries` property, when I do the `add to dictionary` action, it deletes the configs I had applied manually. By `cspell.json`, I mean the one whose address I put in `find_json`.
Actually, my main point is that when `add to dictionary` is call, the `cspell.json` file should only be read, that word should be added to its `words`, and the file should be written again with the same contents as before, because only the `words` have changed and nothing else. Only when the entire content is rebuilt that the `cspell.json` file does not exist.

**Comment by davidmh** [comment] 2024-05-10 19:44
I think I understand your problem, but I can't reproduce it. I could only help you if you share a reproducible example.

**Comment by sajadspeed** [comment] 2024-05-10 20:24
OK, thank you very much for your help. If I could, I would try to read the source of the project and apply these changes.

**Comment by davidmh** [comment] 2024-05-11 21:27
Hi @sajadspeed, I've tried to reproduce your issue once again without success. I'll close this issue for now, but please feel free to open it again if you can share a reproducible example. Or better yet, a PR!

For context, this is the action that deals with adding words to a dictionary: https://github.com/davidmh/cspell.nvim/blob/main/lua/cspell/code_actions/make_add_to_dictionary_action.lua

And this is the action that adds a word to the cspell config: https://github.com/davidmh/cspell.nvim/blob/main/lua/cspell/code_actions/make_add_to_json.lua

**Closed as completed by davidmh** 2024-05-11 21:27 UTC
Labels: needs more info, can't reproduce
