### ISSUE TITLE
[question] code action bug

### ISSUE THREAD

**Issue by ievgenii-shepeliuk** [davidmh/cspell.nvim#32] opened 2023-11-16 11:40 UTC
Hello @davidmh 

I'm experiencing a bug in "Add %word% to cspell json file" code action.
To be able to provide proper PR, I need some feedback from you regarding this place in code

https://github.com/davidmh/cspell.nvim/blob/main/lua/cspell/code_actions/init.lua#L88

My bug is related to the situation while `get_word` function returns improper misspelled word,
i.e. that word differs from one detected by `cspell`.

So my question is, why don't we leverage `diagnostic.user_data.misspelled` instead ?
In my case that field contains a proper word, detected by cspell.

Can you clarify this, so I'd better understand how to address the bug.

Attaching sample file to reproduce.
[test.md](https://github.com/davidmh/cspell.nvim/files/13377207/test.md)

And the screenshot to better explain the issue
![image](https://github.com/davidmh/cspell.nvim/assets/86224637/a0bbacdf-1ecb-45f6-860d-090ec7db2021)

**Comment by eshepelyuk** [comment] 2023-11-16 17:14
Did some more investigation. The problem goes down to diagnostics creation.
When a line contains non latin (unicode ?) characters - the start and end column attributes of the diagnostics may be broken.

**Comment by davidmh** [comment] 2023-11-17 04:19
Hi @eshepelyuk

Looks like that's a long standing problem with null-ls that seems to still live in none-ls, see: https://github.com/jose-elias-alvarez/null-ls.nvim/issues/1630

But there is something we can do to at least fix the code actions in this plugin.

The only reason we pull the word from the buffer using the diagnostic range is because right after we execute the code action, we re-insert the original word into the buffer, only to trigger a new dignostic from cspell.

But as you mention, we can pull the misspelled word from the diagnostics and use that to run the code action. We would still use the word from the diagnostic range for the re-insertion.

That means the diagnostic range will still be wrong, but the code actions will work as expected.

I'll push a fix soon.

We should also forward that null-ls issue to the none-ls maintainers.

**Comment by davidmh** [comment] 2023-11-17 04:31
Should be resolved by #33

**Closed as completed by davidmh** 2023-11-17 04:31 UTC

**Comment by eshepelyuk** [comment] 2023-11-17 04:40
> Should be resolved by #33 

Don't you also need to add user_data extraction here ?

https://github.com/davidmh/cspell.nvim/blob/main/lua/cspell/diagnostics/init.lua#L102

**Comment by davidmh** [comment] 2023-11-17 05:38
Why?

That's the matcher for the diagnostics without suggestions, if we don't have suggestions, then we don't have code actions, if we don't have code actions, we don't need the user_data.

**Comment by eshepelyuk** [comment] 2023-11-17 05:41
> Why?
> 
> That's the matcher for the diagnostics without suggestions, if we don't have suggestions, then we don't have code actions, if we don't have code actions, we don't need the user_data.

If we don't have suggestions we still may want to add a word to cspell.json config\custom dictionary, i.e. has one code action

**Comment by davidmh** [comment] 2023-11-17 05:43
~Ah, good point. I'll push it in a minute.~

Upon further inspection, we may not need this at all. This is the scenario I created, having the following diagnostic:

<img width="981" alt="Screenshot 2023-11-16 at 21 56 52" src="https://github.com/davidmh/cspell.nvim/assets/594302/34eceee4-b39b-4065-b997-88b97cee6242">

There's no suggestion for that word, but the result is still parsed by matcher that looks for suggestions, which means that it will receive the `user_data` table.

The only other case I can think of for a diagnostic to be matched by the matcher without `user_data` is:

<img width="839" alt="Screenshot 2023-11-16 at 22 00 34" src="https://github.com/davidmh/cspell.nvim/assets/594302/5f39e4e6-340f-4a5b-8986-35dc3c852474">

In that case, there's no suggestions, but there's also no code actions to add the exception.

If that's not the scenario you were describing, could you recreate what you mean using http://github.com/davidmh/cspell-nvim-minimal-init?

**Comment by eshepelyuk** [comment] 2023-11-17 06:17
I dont have reproducible scenarios in mind :(
It was just a common sense suggestion.

What is the difference about those 2 input documents, why cspell output differs ?

**Comment by davidmh** [comment] 2023-11-17 06:21
> What is the difference about those 2 input documents, why cspell output differs ?

The second one doesn't have the `show-suggestions` flag in the cspell command.

**Comment by eshepelyuk** [comment] 2023-11-17 06:24
> > What is the difference about those 2 input documents, why cspell output differs ?
> 
> The second one doesn't have the `show-suggestions` flag in the cspell command.

Got the point :)))
Then, can you please add a comment to a source code that 2nd regex parser is used only when code action is not enabled ?

**Comment by davidmh** [comment] 2023-11-17 06:35
I'll keep it on deck to add on the next commit fix or feature.
