### ISSUE TITLE
How does the config file gets to cSpell?

### ISSUE THREAD

**Issue by buschco** [davidmh/cspell.nvim#12] opened 2023-05-15 10:23 UTC
For the builtin cSpell plugin form `null-ls` I used to use the `extra_args` option:

```
null_ls.builtins.diagnostics.cspell.with({
  extra_args = { "--config", vim.fn.expand("~/.cspell.json") },
})
```

I quickly searched this repo for `-c` and `--config`, because as far as I know this is the only way to configure cSpell (https://github.com/streetsidesoftware/cspell/tree/main/packages/cspell#customization), and I found nothing.

So how do you achieve the configuration of cSpell.

**Comment by davidmh** [comment] 2023-05-16 02:17
Hi @buschco, the cspell cli looks for configuration file using the [cosmiconfig](https://www.npmjs.com/package/cosmiconfig) library, see: 

- https://github.com/streetsidesoftware/cspell/blob/88bead744497c47bcc01ac806051ce68081d2164/packages/cspell-lib/src/lib/Settings/Controller/configLoader/configLoader.ts
- https://github.com/streetsidesoftware/cspell/blob/88bead744497c47bcc01ac806051ce68081d2164/packages/cspell-tools/src/build.ts

Which should be able to pickup your configuration file without having to set a `--config` param, as long as the config file matches one of the paths expected my their cosmiconfig setup.

That being said, some actions in this plugin and null-ls in general require you to specify which config file you want to use, for example, the `find_json` property in the [config options](https://github.com/davidmh/cspell.nvim#configuration-options).

What specific problems are you running into?

**Comment by ghidalgo93** [comment] 2023-05-16 02:51
Can confirm, having the same issue, the following minimal config does not work, it _will_ add the word to the correct cspell config dictionary, however diagnostics does not pick it up:
```
local cspell_config = {
	find_json = function(cwd)
		return "/Users/me/.dots/cspell.json"
	end,
}
local cspell = require("cspell")
null_ls.setup({
	sources = {
		cspell.diagnostics.cspell.with({ config = cspell_config }),
		cspell.code_actions.with({ config = cspell_config }),
	},
})
```

I need to pass in the extra args with `--config` in order for diagnostics to pick up the correct cspell config file:
```
local cspell_config = {
	find_json = function(cwd)
		return "/Users/me/.dots/cspell.json"
	end,
}
local cspell = require("cspell")
null_ls.setup({
	sources = {
		null_ls.builtins.diagnostics.cspell.with({
			extra_args = { "--config", "/Users/me/.dots/cspell.json" },
		}),
		cspell.code_actions.with({ config = cspell_config }),
	},
})
```

Edit:

In fact `cspell.diagnostics` is also giving me problems, the sources have to be formatted in the following way to function correctly:
```
null_ls.builtins.diagnostics.cspell.with({
	extra_args = { "--config", "/Users/me/.dots/cspell.json" },
}),

```

**Comment by davidmh** [comment] 2023-05-16 03:19
Thanks @ghidalgo93, I can reproduce the problem. And the great news is that #11 seems to solve this issue, I'll run a few manual tests locally before merging it.

**Comment by davidmh** [comment] 2023-05-16 05:46
Resolved in #11

**Closed as completed by davidmh** 2023-05-16 05:46 UTC
Labels: bug

**Comment by buschco** [comment] 2023-05-16 09:17
Nice works like a charm thank you!

Just to keep in mind: You need an up-to-date version of cSpell installed (`6.18.1` was not working for me, `6.31.1` is working)

**Comment by ghidalgo93** [comment] 2023-05-16 13:25
Also confirming! The following config works for me:

```
local cspell_config = {
	find_json = function(cwd)
		return "/Users/me/.dots/cspell.json"
	end,
}
local cspell = require("cspell")
null_ls.setup({
	sources = {
		cspell.diagnostics.with({ config = cspell_config }),
		cspell.code_actions.with({ config = cspell_config }),
	},
})
```

Thank you for your quick work!
